### ISSUE TITLE
New engine update causing segfault

### ISSUE THREAD

**Issue by 4n6analist** [taviso/loadlibrary#34]
Just noticed this.  The Excel file has been used to test the update and worked previously.   Not sure how to debug. 

2017-08-29 08:53:20 (6.24 MB/s) - ‘mpam-fe.exe’ saved [141828368/141828368]

Extracting cabinet: mpam-fe.exe
  extracting engine/MPSigStub.exe
  extracting engine/mpavdlta.vdm
  extracting engine/mpasdlta.vdm
  extracting engine/mpavbase.vdm
  extracting engine/mpasbase.vdm
  extracting engine/mpengine.dll

All done, no errors.

:~/loadlibrary$ file fd57a4cba764b6d325bbf3b0b13de014d30a774b
fd57a4cba764b6d325bbf3b0b13de014d30a774b: Composite Document File V2 Document, Little Endian, Os: Windows, Version 6.1, Code page: 1252, Author: contador, Last Saved By: Rafael Lucena, Name of Creating Application: Microsoft Excel, Last Printed: Fri Sep 28 18:17:32 2012, Create Time/Date: Tue Aug 21 12:07:29 2007, Last Saved Time/Date: Fri Sep 28 18:21:41 2012, Security: 0

**c:~/loadlibrary$ ./mpclient fd57a4cba764b6d325bbf3b0b13de014d30a774b
Segmentation fault (core dumped)**

:~/loadlibrary$ exiftool engine/mpengine.dll
ExifTool Version Number         : 10.10
File Name                       : mpengine.dll
Directory                       : engine
File Size                       : 10 MB
File Modification Date/Time     : 2017:08:23 20:05:12-07:00
File Access Date/Time           : 2017:08:29 08:53:38-07:00
File Inode Change Date/Time     : 2017:08:29 08:53:27-07:00
File Permissions                : r--r--r--
File Type                       : Win32 DLL
File Type Extension             : dll
MIME Type                       : application/octet-stream
Machine Type                    : Intel 386 or later, and compatibles
Time Stamp                      : 2017:08:13 09:26:21-07:00
PE Type                         : PE32
Linker Version                  : 14.10
Code Size                       : 9821184
Initialized Data Size           : 906240
Uninitialized Data Size         : 0
Entry Point                     : 0x4e8d30
OS Version                      : 10.0
Image Version                   : 10.0
Subsystem Version               : 5.1
Subsystem                       : Windows command line
File Version Number             : 1.1.14104.0
Product Version Number          : 1.1.14104.0
File Flags Mask                 : 0x003f
File Flags                      : (none)
File OS                         : Windows NT 32-bit
Object File Type                : Dynamic link library
File Subtype                    : 0
Language Code                   : English (U.S.)
Character Set                   : Unicode
Company Name                    : Microsoft Corporation
File Description                : Microsoft Malware Protection Engine
Internal Name                   : mpengine
Legal Copyright                 : © Microsoft Corporation. All rights reserved.
Original File Name              : mpengine.dll
Product Name                    : Microsoft Malware Protection
File Version                    : 1.1.14104.0
Product Version                 : 1.1.14104.0

**Comment by taviso** [comment]
I _think_ I fixed this yesterday, could you try `git pull` and see if it works now?

**Comment by 4n6analist** [comment]
I was hopeful, but, looks like still happening:

:~/loadlibrary$ git pull
remote: Counting objects: 8, done.
remote: Total 8 (delta 7), reused 7 (delta 7), pack-reused 1
Unpacking objects: 100% (8/8), done.
From https://github.com/taviso/loadlibrary
   85a4916..0847ba8  master     -> origin/master
Updating 85a4916..0847ba8
Fast-forward
 peloader/winapi/Files.c          | 7 +++++++
 peloader/winapi/LoadLibrary.c    | 6 +++++-
 peloader/winapi/ProcessThreads.c | 7 +++++++
 peloader/winapi/SystemTime.c     | 6 ++++++
 4 files changed, 25 insertions(+), 1 deletion(-)

:~/loadlibrary$ ./mpclient fd57a4cba764b6d325bbf3b0b13de014d30a774b
Segmentation fault (core dumped)

**Comment by 4n6analist** [comment]
Arrgh, forgot to build.  Now it is working :)

Thanks for the quick fix!

**Comment by taviso** [comment]
Cool, no problem, let me know if something breaks again!
